# Adapted from https://github.com/guysoft/OctoPi/blob/devel/.github/workflows/build.yml/
name: Build Raspbian Image

on: 
  push:
    paths:
      - client-builder/src/**
      - .github/workflows/client-builder.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout FullPageOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/FullPageOS'
        path: FullPageOS

    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        path: repository
        submodules: true

    - name: Copy FullPageOS Module
      run: |
        cp -r FullPageOS/src/modules/fullpageos repository/client-builder/src/modules/fullpageos

    - name: Cache Raspbian
      id: cache-raspbian
      uses: actions/cache@v2
      with:
        path: repository/client-builder/src/image/2021-05-07-raspios-buster-armhf-lite.zip
        key: ${{ runner.os }}-raspbian

    - name: Download Raspbian Image
      if: steps.cache-raspbian.outputs.cache-hit != 'true'
      run: |
        cd repository/client-builder/src/image
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2021-05-28/2021-05-07-raspios-buster-armhf-lite.zip'

    - name: Download and Unpack AWS IOT Greengrass Core
      run: |
        cd repository/client-builder/src/modules/mindbeamer/filesystem/opt/greengrass
        wget -c --trust-server-names 'https://d2s8p88vqu9w66.cloudfront.net/releases/greengrass-nucleus-latest.zip'
        unzip greengrass-nucleus-latest.zip
        rm greengrass-nucleus-latest.zip

    - name: Download Provisioning USB GPG Key
      run: |
        cd repository/client-builder/src/modules/mindbeamer/filesystem/opt/mindbeamer
        wget -c --trust-server-names 'https://keybase.io/spriggs/pgp_keys.asc'
        gpg --no-default-keyring --keyring ./signer.kbx --import ./pgp_keys.asc

    - name: Update CustomPiOS Paths
      run: |
        cd repository/client-builder/src
        ../../../CustomPiOS/src/update-custompios-paths
    
    - name: Force apt mirror to work around intermittent mirror hiccups
      run: |
        echo "OCTOPI_APTMIRROR=http://mirror.us.leaseweb.net/raspbian/raspbian" > repository/client-builder/src/config.local

    - name: Set OS Build file
      run: |
        cd repository/client-builder/src/modules/mindbeamer/filesystem/opt/mindbeamer
        echo "mindbeamer-os-$(git rev-parse --short "$GITHUB_SHA") > os-build"

    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/client-builder/src
        sudo bash -x ./build_dist

    - name: Copy output
      id: copy
      run: |
        source repository/client-builder/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        IMAGE=$NOW-mindbeamer-$DIST_VERSION

        cp repository/client-builder/src/workspace/*.img $IMAGE.img

        echo "::set-output name=image::$IMAGE"

    # artifact upload will take care of zipping for us
    - uses: actions/upload-artifact@v1
      #if: github.event_name == 'schedule'
      with:
        name: ${{ steps.copy.outputs.image }}
        path: ${{ steps.copy.outputs.image }}.img
