name: Build Frontend Package

on: 
  push:
    paths:
      - frontend/**
      - examples/**
      - .github/workflows/frontend-package.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static
    - name: Checkout Project Repository
      uses: actions/checkout@v2
    - name: Set Node Version
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.2'
    - name: Get SHA
      id: get_sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short "$GITHUB_SHA")"
    - name: Prepare examples directory
      run: |
        cd examples
        npm install --only=production
    - name: Package frontend
      run: |
        mkdir build
        zip -r build/mindbeamer-${{ steps.get_sha.outputs.short-sha }}.zip frontend examples
    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: "${{ secrets.AWS_KEY_ID }}"
        aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws_bucket: mindbeamer
        source_dir: build
        destination_dir: ''
    - name: Update Greengrass v2 Component
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        GIT_TAG=$(echo $GITHUB_REF | cut -d / -f 3)
        GIT_HASH=${{ steps.get_sha.outputs.short-sha }}
        sed -i "s/GIT_TAG/$GIT_TAG/g" greengrass.json
        sed -i "s/GIT_HASH/$GIT_HASH/g" greengrass.json
        aws greengrassv2 create-component-version --inline-recipe fileb://greengrass.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'
