name: Build Frontend Package

on: 
  push:
    paths:
      - frontend/**
      - examples/**
      - .github/workflows/frontend-package.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static
    - name: Checkout Project Repository
      uses: actions/checkout@v2
    - name: Get SHA
      id: get_sha
      run: echo "::set-output name=short-sha::$(git rev-parse --short "$GITHUB_SHA")"
    - name: Prepare examples directory
      run: |
        cd examples
        npm install --only=production
    - name: Install dependencies
      run: |
        cd frontend
        npm install --only=production
    - name: Run npm build
      run: |
        cd frontend
        npm run build
    - name: Package frontend
      run: |
        mkdir build
        zip -r build/mindbeamer-${{ steps.get_sha.outputs.short-sha }}.zip frontend examples
    - name: Upload to S3
      uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: "${{ secrets.AWS_KEY_ID }}"
        aws_secret_access_key: "${{ secrets.AWS_SECRET_ACCESS_KEY}}"
        aws_bucket: mindbeamer
        source_dir: build
        destination_dir: ''
